.PHONY: build

build:
	rm -f __FILE-NAME__.aux __FILE-NAME__.log __FILE-NAME__.out __FILE-NAME__.toc
	lualatex __FILE-NAME__.tex
	lualatex __FILE-NAME__.tex
	lualatex __FILE-NAME__.tex
	rm -f __FILE-NAME__.aux __FILE-NAME__.log __FILE-NAME__.out __FILE-NAME__.toc
